use [EX1DB]
go

INSERT INTO [dbo].[User](nombre,apellido,email,password)
VALUES
    ('VICTOR','CALDERON','VICDERON@HOTMAIL.COM','vic12345'),
    ('JESSIE','FADEN','JFADEN@LIVE.COM','JF555'),
    ('JONH','SMITH','SMITH37@GMAIL.COM','PF51015'),
    ('FRANK','WATTERSON','FRANKIEW@HOTMAIL.COM','FW303'),
	('DYLAN','SMITH','DSMITH@LIVE.COM','DL5485')